### ISSUE TITLE
What are the downstream pkgs for processing/analysis?

### ISSUE THREAD

**Issue by sckott** [ropensci/getlandsat#1]
want to make sure outputs are useful

**Comment by sckott** [comment]
@lawinslow

**Comment by lawinslow** [comment]
Wow, that was quick!

Packages that should probably play well:
rgdal
raster
landsat

not on cran:
https://github.com/dutri001/bfastSpatial

Those are the ones I know or can come up off the top of my head. I'll try to spread the word and see if others have suggestions.

**Comment by sckott** [comment]
Nice, thanks !

**Comment by pierreroudier** [comment]
satellite (package building on raster)

**Comment by sckott** [comment]
great, thanks @pierreroudier !

will think about these pkgs and how we can make it easier to go from this pkg to those others
