### ISSUE TITLE
Q: re projection

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/getlandsat#11]
I noticed that the projection of the scenes downloaded by the package is WGS84 - to check, these are reprojected scenes, yes? As the originals I've gotten from NASA/USGS in the past are in UTM, not stere as put up here. Have the scenes to download been reprojected?

**Comment by sckott** [comment]
@jebyrnes thanks for the question. What function are you talking about?

**Comment by sckott** [comment]
Looking at code, pretty sure we simply download files and that's it.

**Comment by jebyrnes** [comment]
Huh - well that makes me nervous. About other projects.

Talking about `lsat_image()`

**Comment by lawinslow** [comment]
They may have projected them differently up on AWS. Description is light on details
https://aws.amazon.com/public-data-sets/landsat/

**Comment by sckott** [comment]
thanks @lawinslow for chiming in. Will keep digging...

**Comment by sckott** [comment]
@jebyrnes I guess we should be downloading the metadata file (`.IMD`) too by default and present the most useful metadata to the user along with path to the file, file size

will open a new issue for that. 

relavant bits from one metadata file:

```
PROJECTION_PARAMETERS.DATUM = "WGS84";
PROJECTION_PARAMETERS.ELLIPSOID = "WGS84";
PROJECTION_PARAMETERS.MAP_PROJECTION = "UTM";
PROJECTION_PARAMETERS.UTM_ZONE = 30;
```

So it says WGS84 datum, and UTM map projection - no clue about whether been reprojected or not
