### ISSUE TITLE
Can we pseudo-cache the Landsat layers?

### ISSUE THREAD

**Issue by lawinslow** [ropensci/getlandsat#2]
Just a thought, if subsequent calls to `lsat_image` for the same file used a locally cached version instead of re-downloading. 

Low priority.

**Comment by sckott** [comment]
:+1: 

hadn't gotten to this yet, but a definite must

**Comment by sckott** [comment]
@lawinslow okay, reinstall and try - hopefully it doesn't bug out on windows, havent tested on windows yet

**Comment by sckott** [comment]
switch to using `rappdirs` for caching

**Comment by sckott** [comment]
done
