### ISSUE TITLE
Landsat scene discovery

### ISSUE THREAD

**Issue by pierreroudier** [ropensci/getlandsat#23]
Hi,

Is it within the scope of the package to build a function to discover scenes that are matching a given spatial extent?

Use case: I have the bounding box of my region of interest, and I am wanting to list all the Landsat scenes available over that bounding box.

Cheers,

**Comment by sckott** [comment]
👋  @pierreroudier  thanks for the issue

Yes, i think it's in scope. 

AFAIK there's no way to do this with the interface we're using - that is, the Amazon S3 API service - do you know of any way to do it?

**Comment by pierreroudier** [comment]
@sckott well, not sure TBH -- there's [this link](https://landsat.usgs.gov/what-worldwide-reference-system-wrs) to about cataloging.

**Comment by sckott** [comment]
hmm, that site isn't loading right now, will try again later

**Comment by sckott** [comment]
hmm, so `lsat_scenes` fxn grabs the list of scenes from http://landsat-pds.s3.amazonaws.com/scene_list.gz which does have extent data for each image in it. (whereas `lsat_list` function uses S3 API, and no spatial data is included there)

with `lsat_scenes` we can probably build do the spatial query locally in R, using some spatial pkgs

**Comment by sckott** [comment]
@mdsumner  question about spatial operation - want to find overlap of a bounding box defined by a user as input to a function and about a million bounding boxes defined for each of the LANDSAT images. 

e.g. heres the top of the data.frame of landsat scenes - converting one row at a time to a polygon takes a long time - then doing an overlap comparison for each one of those also takes a long time - is there anyway to do all comparisons in the 1 million row data.frame to the user supplied bbox that is fast?

```r
# A tibble: 1,059,757 x 11
                entityId     acquisitionDate cloudCover processingLevel  path   row   min_lat    min_lon   max_lat    max_lon
                   <chr>              <dttm>      <dbl>           <chr> <int> <int>     <dbl>      <dbl>     <dbl>      <dbl>
 1 LC80101172015002LGN00 2015-01-02 15:49:05      80.81            L1GT    10   117 -79.09923 -139.66082 -77.75440 -125.09297
 2 LC80260392015002LGN00 2015-01-02 16:56:51      90.84            L1GT    26    39  29.23106  -97.48576  31.36421  -95.16029
 3 LC82270742015002LGN00 2015-01-02 13:53:02      83.44            L1GT   227    74 -21.28598  -59.27736 -19.17398  -57.07423
 4 LC82270732015002LGN00 2015-01-02 13:52:38      52.29             L1T   227    73 -19.84365  -58.93258 -17.73324  -56.74692
 5 LC82270622015002LGN00 2015-01-02 13:48:14      38.85             L1T   227    62  -3.95294  -55.38896  -1.84491  -53.32906
```

**Comment by pierreroudier** [comment]
@sckott the latest version of `sf` dies support spatial indexing. Could you post a quick piece of code to get that 1 million row tibble? I might try a few things.

**Comment by sckott** [comment]
`readr::read_csv("http://landsat-pds.s3.amazonaws.com/scene_list.gz")`

i'd prefer not to depend on `sf` though since requires gdal - but could give examples in the  README for doing that

**Comment by mdsumner** [comment]
Straight extent comparison with raster should be fast enough, but is the geometry of that rectangle sufficient to describe the region? You can trim to candidate extents by direct xmin/xmax/ymin/ymax comparison.  sp::over is also as fast as you can get with Spatial get as it does bounding box overlap filters (whatever is the right way to say, that "spatial indexing" basically) - even with massive data set decomposition and re-creation of millions of triangles for example, sp::over beat anything else. 

I'll try a few things too ;)

**Comment by mdsumner** [comment]
I get this: 

```
scenes <- readr::read_csv("http://landsat-pds.s3.amazonaws.com/scene_list.gz")
Error: Unknown TZ UTC
```

could you saveRDS instead? Or email?

**Comment by mdsumner** [comment]
I can fix with col_types over ride

**Comment by mdsumner** [comment]
This is a bit over-wrought, I can tidy it up a lot more ...
`exes0` is all the candidate extents, so it trims the huge set to compare quite a lot which will make the intersection testing faster, and the final set is in `exes`. Obviously you need to apply this back up to classify the big table, but it's workable enough I think.  

```R
cls <- readr::cols(entityId = "c", 
         acquisitionDate = "c",  
         cloudCover = "d",  
         processingLevel = "c", 
         path = "i", 
         row = "i", 
         min_lat = "d", 
         min_lon = "d", 
         max_lat = "d", 
         max_lon = "d")

scenes <- readr::read_csv("http://landsat-pds.s3.amazonaws.com/scene_list.gz", col_types = cls)
ex <- raster::extent(140, 150, -50, -30)
library(dplyr)
library(raster)

scenes_filtered <- scenes %>% dplyr::filter(min_lon >= xmin(ex), max_lat <= xmax(ex), 
                         min_lat >= ymin(ex), max_lat <= ymax(ex)) %>% 
  dplyr::transmute(min_lon, max_lon, min_lat, max_lat, row = row_number())

rex <- function(min_lon, max_lon, min_lat, max_lat) {
  raster::extent(c(min_lon, max_lon, min_lat, max_lat))
}
exes0 <- lapply(split(scenes_filtered %>% dplyr::select(min_lon, max_lon, min_lat, max_lat), scenes_filtered$row), function(x) do.call(rex, x))

target_scenes <- scenes_filtered %>% 
  dplyr::filter(unlist(lapply(exes0, function(target) length(raster::intersect(target, ex)) > 0)))

## final trim
exes <- lapply(split(target_scenes %>% dplyr::select(min_lon, max_lon, min_lat, max_lat), 
                     target_scenes$row), function(x) do.call(rex, x))

plot(ex)
purrr::walk(exes, plot, add = TRUE, col = grey(0.1, alpha = 0.1))

maps::map()
purrr::walk(exes, plot, add = TRUE, col = grey(0.1, alpha = 0.1))

purrr::reduce(exes, raster::union)
#class       : Extent 
#xmin        : 140.075 
#xmax        : 152.5469 
#ymin        : -45.68039 
#ymax        : -30.63774 
```

**Comment by sckott** [comment]
@mdsumner thanks! forgot about `over`, will have a look at that first since it is simple

**Comment by sckott** [comment]
sorry for delay @pierreroudier - meaning to get back to this, just a hard problem

**Comment by mdsumner** [comment]
Keep me in the loop, I've been exploring this kind of thing a lot. Having a lightweight point-wise over() is something I need here and there. It's also very tidyverse-y, using group_by to control hierarchies of lower level simple intersection tests.

**Comment by sckott** [comment]
hi all, moved work on this to another branch off master https://github.com/ropenscilabs/getlandsat/tree/lsat_scenes-changes 

pushed master back to state before any of the above changes were made

**Comment by sckott** [comment]
Sorry again about delay, combo of very busy and hard enough that I haven't gotten around to this. hopefully soon, unless someone else has a solution?

**Comment by maelle** [comment]
this repository is about to be archived
