### ISSUE TITLE
lsat_search not functional?

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/getlandsat#28]
Tried the readme, and got this

```
> x <- lsat_search(collection = "landsat-8", cloud_cover = c(0, 20), limit = 3)$features
> 
> x
NULL
> names(x)
NULL
```

API problems?

I was working on some of my own stuff, and got the following

```
> recs <- lsat_search(collection = "landsat-8", row = 30, path = 12)
> recs
$links
                                             href     rel
1             https://sat-api.developmentseed.org    self
2 https://sat-api.developmentseed.org/collections    data
3             http://sat-utils.github.io/sat-api/ service
```

So, better? But, something isn't connecting here.

**Comment by sckott** [comment]
👋🏽  nice to hear from you. hey i've moved on to another job and no longer doing R things for the most part. You interested in taking over this pkg?

**Comment by sckott** [comment]
or maybe you have a student/post-doc that might be

**Comment by maelle** [comment]
this repository is about to be archived
