### ISSUE TITLE
What are .ovr files?

### ISSUE THREAD

**Issue by sckott** [ropensci/getlandsat#5]
should they be treated in any special way?

**Comment by lawinslow** [comment]
From website

> .TIF.ovr overview file for each .TIF (useful in GDAL based applications)

I poked around to see if rgdal can use .ovr files. Didn't find an answer, but I did find this

> The GeoTIFF driver supports reading, creation and update of internal overviews. Internal overviews can be created on GeoTIFF files opened in update mode (with gdaladdo for instance). If the GeoTIFF file is opened as read only, the creation of overviews will be done in an external .ovr file. Overview are only updated on request with the BuildOverviews() method.

I'd say skip it for now. They don't have any info that the tiff's don't have and I'm not convinced rgdal can use them anyway.

**Comment by sckott** [comment]
okay, thanks @lawinslow

**Comment by sckott** [comment]
closing for now, can re-visit if someone wants these later
